stage:
  spm-test:
    prepare:
      exec:
      - "yum erase -y alinode-iojs && rm -f /opt/taobao/node"
      - "yum install -y alinode-iojs-0.12.* -b current"
      - "PATH=/opt/taobao/node/bin:$PATH npm i tnpm -g --registry=http://registry.npm.alibaba-inc.com"
      - "PATH=/opt/taobao/node/bin:$PATH tnpm -v"
      - "PATH=/opt/taobao/node/bin:$PATH tnpm i"
      - "PATH=/opt/taobao/node/bin:$PATH tnpm i spm -g"
      - "PATH=/opt/taobao/node/bin:$PATH spm i"
    unit_test:
      exec:
      - "PATH=/opt/taobao/node/bin:$PATH tnpm test"
pipeline:
- spm-test
